services:
    tanks-server:
        image: wlczak/go-tanks:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true
        # volumes:
        #     - ./:/app
        working_dir: /app
        restart: always
        ports:
            - "9460:8080"
        command: ./tanks
