services:
    tanks-server:
        image: golang:1.24.2-alpine3.21
        volumes:
            - ./:/app
        working_dir: /app
        restart: always
        user: "${UID}:${GID}"
        environment:
            - UID=${UID}
            - GID=${GID}
        ports:
            - "9460:8080"
        command: go run .
