services:
    tanks-server:
        image: golang:1.24.5-alpine3.22
        volumes:
            - ./:/app
        working_dir: /app
        restart: always
        ports:
            - "9460:8080"
        command: go run .
