services:
    tanks-server:
        image: wlczak/go-tanks:latest
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            # - ./:/app
            - ./logger/logs:/app/logger/logs
        working_dir: /app
        restart: always
        ports:
            - "9460:8080"
        command: ./tanks
networks:
    tanks-net:
        name: tanks-net
