name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: ["*"]

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: game/package-lock.json

            - run: npm ci

            - name: TypeScript validation
              run: npx tsc --noEmit

            - name: ESLint linting
              run: npx eslint "src/**/*.ts" --max-warnings=0
